server:
  servlet:
    context-path: /api
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/load-testing
    username: postgres
    password: duchuy
    hikari:
      max-lifetime: 60000
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: development
    drop-first: false
  data:
    redis:
      host: localhost
      port: 6379