server:
  servlet:
    context-path: /api
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-hexagonal
    username: postgres
    password: duchuy
    hikari:
      max-lifetime: 60000
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    mode: HTML